image: openjdk:8

stages:
  - build
  - test
  - analysis

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GIT_SUBMODULE_STRATEGY: normal

Build:
  stage: build
  script:
    - ./gradlew --no-daemon --max-workers=1 assemble
  artifacts:
    paths:
      - build
  tags: ["default"]

Test:
  stage: test
  script:
    - ./gradlew --no-daemon --max-workers=1 check
  artifacts:
    paths:
      - build
    reports:
      junit: build/test-results/test/TEST-*.xml
  tags: ["default"]

Coverage:
  stage: analysis
  script:
    - ./gradlew --no-daemon --max-workers=1 jacocoTestReport
    - cat build/jacocoHtml/index.html || true
  coverage: "/Total.*?([0-9]{1,3})%/"
  tags: ["default"]
